#FROM php:7.0-apache
FROM php:5.6.30-apache

COPY backports.list /etc/apt/sources.list.d/

RUN apt-get update && apt-get install -y \
      wget &&\
      apt-get install -y python-certbot-apache -t jessie-backports

ENV USERNAME pmwiki
ENV USERID 1000
ENV GROUPID 1000
ENV GROUPNAME pmwiki
ENV APACHE_RUN_USER $USERNAME

RUN addgroup --gid $GROUPID $GROUPNAME && adduser --uid $USERID --gid $GROUPID --no-create-home --disabled-login --quiet $USERNAME
RUN addgroup --quiet $USERNAME www-data

RUN a2enmod rewrite

VOLUME ["/var/www/html"]

